import { useEffect, useMemo, useState } from 'react'
import { Button, Form, Input, Select } from 'antd'
import toast from 'react-hot-toast'
import api from '../api'
import { useAuth } from '../context/AuthContext'
import {
  isAutoGeneratedPortalId,
  isReservedPortalSegment,
  markPulseAccountCreated,
  normalizePulsePortalId,
  portalIdFromCompanyName,
  suggestPulsePortalId,
} from '../utils/pulseEntry'

export const INDUSTRIES = [
  'Agriculture',
  'Art, Architecture & Design',
  'Automotive',
  'Aviation / Aerospace',
  'Banking',
  'Biotechnology',
  'Chemicals',
  'Construction / Real Estate',
  'Consulting',
  'Consumer Goods',
  'E-Commerce',
  'Education',
  'Electronics',
  'Energy / Oil & Gas',
  'Entertainment / Media',
  'Finance / BFSI',
  'Food & Beverage',
  'Government / Public Sector',
  'Healthcare',
  'Hospitality / Travel',
  'Information Technology (IT)',
  'Insurance',
  'Internet / Web Services',
  'Legal',
  'Logistics / Supply Chain',
  'Manufacturing',
  'Marketing / Advertising',
  'Mining / Metals',
  'Non-profit / NGO',
  'Pharmaceuticals',
  'Product / SaaS',
  'Retail',
  'Software Development',
  'Software / Technology',
  'Startups',
  'Telecom',
  'Technology / IT Services',
  'Textiles / Apparel',
  'Transportation',
  'Utilities',
  'Other',
]

const PORTAL_MIN = 6
const PORTAL_MAX = 50
const PORTAL_LEN_MSG = 'Portal name must have minimum of 6 and maximum of 50 characters'

function portalLengthError(portalId) {
  const len = String(portalId || '').trim().length
  if (len === 0) return ''
  if (len < PORTAL_MIN || len > PORTAL_MAX) return PORTAL_LEN_MSG
  return ''
}

export default function PulseCompanyInfoForm({ user }) {
  const { updateProfile } = useAuth()
  const [form] = Form.useForm()
  const [saving, setSaving] = useState(false)
  const [portalTouched, setPortalTouched] = useState(false)
  const industryOptions = useMemo(
    () => INDUSTRIES.map((item) => ({ value: item, label: item })),
    [],
  )

  useEffect(() => {
    if (!user) return
    const starter = suggestPulsePortalId(user)
    form.setFieldsValue({
      companyName: user.companyName || '',
      portalId: starter,
      industry: user.industry || undefined,
      employeeCount: user.pulseEmployeeCount || '',
    })
    setPortalTouched(Boolean(starter && !isAutoGeneratedPortalId(user.pulsePortalId)))
  }, [user, form])

  const onCompanyChange = (companyName) => {
    if (portalTouched) return
    const fromCompany = portalIdFromCompanyName(companyName)
    if (fromCompany) form.setFieldValue('portalId', fromCompany)
  }

  const onSave = async (values) => {
    if (saving) return
    const companyName = String(values.companyName || '').trim()
    if (!companyName) {
      toast.error('Enter company name.')
      return
    }
    let portal = normalizePulsePortalId(String(values.portalId || '').trim())
    if (!portal || isAutoGeneratedPortalId(portal)) {
      portal = portalIdFromCompanyName(companyName)
    }
    if (!portal) {
      form.setFields([{ name: 'portalId', errors: [PORTAL_LEN_MSG] }])
      return
    }
    if (isReservedPortalSegment(portal)) {
      form.setFields([{ name: 'portalId', errors: ['This Portal Name is reserved. Choose another.'] }])
      return
    }
    const lenErr = portalLengthError(portal)
    if (lenErr) {
      form.setFields([{ name: 'portalId', errors: [lenErr] }])
      return
    }
    if (!values.industry) {
      toast.error('Select an industry.')
      return
    }
    if (!String(values.employeeCount || '').trim()) {
      toast.error('Enter employee count.')
      return
    }
    setSaving(true)
    try {
      const res = await api.post('/auth/pulse-setup', {
        companyName,
        portalId: portal,
        industry: values.industry,
        employeeCount: String(values.employeeCount).trim(),
      })
      const nextUser = { ...res.data.user, pulseSetupCompleted: true, pulsePortalId: portal }
      markPulseAccountCreated(portal)
      updateProfile(nextUser)
      toast.success('Company information saved')
    } catch (err) {
      const msg = err.response?.data?.message || 'Could not save company information'
      const code = err.response?.data?.code
      if (code === 'PORTAL_EXISTS' || /already exists/i.test(msg)) {
        form.setFields([{ name: 'portalId', errors: ['This Portal Name already exists'] }])
      } else if (code === 'PORTAL_LENGTH' || /minimum of 6/i.test(msg)) {
        form.setFields([{ name: 'portalId', errors: [PORTAL_LEN_MSG] }])
      } else {
        toast.error(msg)
      }
    } finally {
      setSaving(false)
    }
  }

  return (
    <Form
      form={form}
      layout="vertical"
      className="pulse-org-info-form"
      requiredMark
      onFinish={onSave}
    >
      <Form.Item
        name="companyName"
        label="Company name"
        rules={[{ required: true, message: 'Company name is required' }]}
      >
        <Input
          autoComplete="organization"
          onChange={(event) => onCompanyChange(event.target.value)}
        />
      </Form.Item>
      <Form.Item
        name="portalId"
        label="Portal name"
        rules={[{ required: true, message: 'Portal name is required' }]}
      >
        <Input
          autoComplete="off"
          maxLength={PORTAL_MAX}
          onChange={() => setPortalTouched(true)}
        />
      </Form.Item>
      <Form.Item
        name="industry"
        label="Industry"
        rules={[{ required: true, message: 'Select an industry' }]}
      >
        <Select
          placeholder="Select"
          options={industryOptions}
          showSearch
          optionFilterProp="label"
        />
      </Form.Item>
      <Form.Item
        name="employeeCount"
        label="Employee count"
        rules={[{ required: true, message: 'Employee count is required' }]}
      >
        <Input inputMode="numeric" autoComplete="off" />
      </Form.Item>
      <Button type="primary" htmlType="submit" loading={saving}>
        {saving ? 'Saving' : 'Save'}
      </Button>
    </Form>
  )
}
