// Getting Started path helper — parked on branch `pulse/company-later-services`.
// const PULSE_GETTING_STARTED_SUFFIX = '/settings/service/getting-started'

/** Paths that must never be treated as a portal name. */
const RESERVED_PORTAL_SEGMENTS = new Set([
  'login',
  'register',
  'account',
  'apps',
  'portal',
  'pulse',
  'bda-os',
  'bdaos',
  'people',
  'setup',
  'oauth',
  'coming-soon',
  'smart-signin',
  'people-os',
  'dashboard',
  'staff',
  'payslips',
  'performance',
  'attendance',
  'leave',
  'settings',
  'tasks',
  'forgot',
  'reset-password',
  'verify',
  'verify-email',
  'invite',
  'onboard',
  'api',
])

export const APP_BASE = '/bda-os'
export const APP_ROOT = APP_BASE
export const APP_COMPANY = `${APP_BASE}/company`
export const APP_NOTES = `${APP_BASE}/notes`
export const APP_TIMER = `${APP_BASE}/checkin-timer`
export const PULSE_HOME = `${APP_BASE}/home`

export function isAppPath(pathname) {
  const path = String(pathname || '').replace(/\/+$/, '') || '/'
  return (
    path === APP_BASE ||
    path.startsWith(`${APP_BASE}/`) ||
    path === '/pulse' ||
    path.startsWith('/pulse/')
  )
}

export function toAppPath(pathname) {
  let path = String(pathname || '')
  if (path === '/pulse' || path.startsWith('/pulse/')) {
    path = path.replace(/^\/pulse/, APP_BASE)
  }
  if (path === `${APP_BASE}/time` || path.startsWith(`${APP_BASE}/time/`)) {
    return path.replace(`${APP_BASE}/time`, `${APP_BASE}/hours`)
  }
  return path
}

export function isBdaOsAppLink(to) {
  const value = String(to || '')
  return (
    value === APP_BASE ||
    value.startsWith(`${APP_BASE}/`) ||
    value === '/pulse' ||
    value.startsWith('/pulse/')
  )
}

export function normalizePulsePortalId(portalId) {
  return String(portalId || '')
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9_-]/g, '')
    .slice(0, 50)
}

/** Timestamp-style auto IDs like 86972825350 - never use these as portal names. */
export function isAutoGeneratedPortalId(portalId) {
  const id = String(portalId || '').trim()
  return /^\d{6,}$/.test(id)
}

export function portalIdFromCompanyName(companyName) {
  return normalizePulsePortalId(companyName)
}

export function suggestPulsePortalId(user) {
  const existing = normalizePulsePortalId(user?.pulsePortalId)
  if (existing && !isAutoGeneratedPortalId(existing) && !isReservedPortalSegment(existing)) {
    return existing
  }
  const fromCompany = portalIdFromCompanyName(user?.companyName)
  if (fromCompany.length >= 6) return fromCompany
  const fromEmail = normalizePulsePortalId(String(user?.email || '').split('@')[0])
  if (fromEmail.length >= 6) return fromEmail
  return fromCompany || fromEmail || ''
}

export function isReservedPortalSegment(segment) {
  const id = normalizePulsePortalId(segment)
  return !id || RESERVED_PORTAL_SEGMENTS.has(id)
}

export function suggestedPulseSetupPayload(user) {
  const companyName = String(user?.companyName || '').trim() || 'My company'
  let portalId = suggestPulsePortalId({ ...user, companyName })
  if (!portalId || portalId.length < 6) {
    portalId = normalizePulsePortalId(`${portalId || 'org'}hq`)
  }
  while (portalId.length < 6) portalId += 'x'
  if (isReservedPortalSegment(portalId)) {
    portalId = normalizePulsePortalId(`${portalId}hq`)
  }
  if (!portalId || portalId.length < 6) portalId = 'orghome'
  return {
    companyName,
    portalId: portalId.slice(0, 50),
    industry: String(user?.industry || '').trim() || 'Other',
    employeeCount: String(user?.pulseEmployeeCount || '').trim() || '1',
  }
}

/**
 * Getting Started URLs — parked on branch `pulse/company-later-services`.
 * Invited employees sign in to My Space (`PULSE_HOME`) and the welcome curtain.
 */
export function getPulseGettingStartedPath(_userOrPortalId) {
  return PULSE_HOME
  /*
  if (userOrPortalId && typeof userOrPortalId === 'object') {
    const portalId = suggestPulsePortalId(userOrPortalId)
    if (!portalId || isReservedPortalSegment(portalId)) {
      return `/pulse${PULSE_GETTING_STARTED_SUFFIX}`
    }
    return `/${portalId}${PULSE_GETTING_STARTED_SUFFIX}`
  }

  const portalId = normalizePulsePortalId(userOrPortalId)
  if (!portalId || isReservedPortalSegment(portalId) || isAutoGeneratedPortalId(portalId)) {
    return `/pulse${PULSE_GETTING_STARTED_SUFFIX}`
  }
  return `/${portalId}${PULSE_GETTING_STARTED_SUFFIX}`
  */
}

/** @deprecated Getting Started parked on `pulse/company-later-services`. */
export const PULSE_GETTING_STARTED = PULSE_HOME

export function hasPulseSampleChoice() {
  try {
    return localStorage.getItem('pulseSampleData') != null
  } catch {
    return false
  }
}

export function getPulseSampleChoice() {
  try {
    return localStorage.getItem('pulseSampleData')
  } catch {
    return null
  }
}

export function hasPulseGuideDismissed() {
  try {
    return localStorage.getItem('pulseGuideDismissed') === '1'
  } catch {
    return false
  }
}

export function dismissPulseGuide() {
  try {
    localStorage.setItem('pulseGuideDismissed', '1')
  } catch {
    /* ignore */
  }
}

/** Allow returning to Getting Started from /pulse. Parked — restore from `pulse/company-later-services`. */
export function reopenPulseGuide() {
  /*
  try {
    localStorage.removeItem('pulseGuideDismissed')
  } catch {
    // ignore
  }
  */
}

/** Clear local Pulse onboarding flags (sample choice / last path). */
export function clearPulseLocalState() {
  try {
    localStorage.removeItem('pulseSampleData')
    localStorage.removeItem('pulseLastPath')
    localStorage.removeItem('pulseGuideDismissed')
  } catch {
    /* ignore */
  }
}

/** True when own-data users still need the Getting Started hub. Parked on `pulse/company-later-services`. */
export function needsPulseGettingStartedGuide() {
  return false
  // return getPulseSampleChoice() === '0' && !hasPulseGuideDismissed()
}

export function markPulseAccountCreated(portalId) {
  try {
    localStorage.setItem('pulseAccountCreated', normalizePulsePortalId(portalId) || '1')
  } catch {
    /* ignore */
  }
}

/** Pulse company account already exists (server flag, portal id, or local save). */
export function hasPulseAccount(user) {
  if (user?.pulseSetupCompleted === true) return true
  const portalId = normalizePulsePortalId(user?.pulsePortalId)
  if (portalId && !isAutoGeneratedPortalId(portalId) && !isReservedPortalSegment(portalId)) {
    return true
  }
  try {
    return !!localStorage.getItem('pulseAccountCreated')
  } catch {
    return false
  }
}

const PULSE_RESUME_PATHS = new Set([PULSE_HOME, APP_COMPANY])
const LEGACY_RESUME_PATHS = {
  '/pulse/home': PULSE_HOME,
  '/pulse/company': APP_COMPANY,
}

/** Where to open BDA OS from the apps launcher / deep links. */
export function getPulseOpenPath(user) {
  if (!hasPulseAccount(user)) return PULSE_HOME
  // Getting Started parked on `pulse/company-later-services`:
  // if (!hasPulseSampleChoice() || needsPulseGettingStartedGuide()) {
  //   return getPulseGettingStartedPath(user)
  // }

  try {
    const last = LEGACY_RESUME_PATHS[localStorage.getItem('pulseLastPath')] || localStorage.getItem('pulseLastPath')
    if (last && PULSE_RESUME_PATHS.has(last)) return last
  } catch {
    /* ignore */
  }

  return PULSE_HOME
}

/** After invite / login / OAuth — open You directly (no marketing landing). */
export function getPostLoginPath(_user) {
  return PULSE_HOME
}

/** Remember last Pulse screen so reopen resumes there. Never persist service URLs. */
export function rememberPulsePath(pathname) {
  if (!pathname) return
  const path = toAppPath(pathname.replace(/\/+$/, '') || '/')
  if (!PULSE_RESUME_PATHS.has(path)) return
  try {
    localStorage.setItem('pulseLastPath', path)
  } catch {
    /* ignore */
  }
}
